name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.docker-image.outputs.image }}

    steps:
      - id: short-sha
        uses: benjlevesque/short-sha@v1.2
      - id: docker-image
        run: |
          IMAGE=registry.${{ secrets.ACR_REGION }}.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_REPO }}:${{ github.run_number }}-${{ steps.short-sha.outputs.sha }}
          echo "::set-output name=image::$IMAGE"

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      IMAGE_DEV: ${{ needs.prepare.outputs.IMAGE }}-dev
      IMAGE_PROD: ${{ needs.prepare.outputs.IMAGE }}-prod

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: docker/setup-buildx-action@v1.6.0
        with:
          driver: docker-container

      - uses: aliyun/acr-login@v1
        with:
          region-id: ${{ secrets.ACR_REGION }}
          access-key-id: ${{ secrets.ACR_AK }}
          access-key-secret: ${{ secrets.ACR_SK }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_DEV }}
          target: development
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: production
          tags: ${{ env.IMAGE_PROD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
