name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: short-sha
        uses: benjlevesque/short-sha@v1.2

      - run: echo "IMAGE=registry.${{ secrets.ACR_REGION }}.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_REPO }}:${{ github.run_number }}-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV
      - run: echo "IMAGE_DEV=${{ env.IMAGE }}-dev" >> $GITHUB_ENV
      - run: echo "IMAGE_DEV=${{ env.IMAGE }}-prod" >> $GITHUB_ENV

      - uses: actions/checkout@v2.4.0

      - uses: aliyun/acr-login@v1
        with:
          region-id: ${{ secrets.ACR_REGION }}
          access-key-id: ${{ secrets.ACR_AK }}
          access-key-secret: ${{ secrets.ACR_SK }}

      - uses: docker/setup-buildx-action@v1.6.0
        # with:
        #   driver: docker-container
        #   driver-opts: |
        #     image=moby/buildkit:master
        #     network=host

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_DEV }}
          target: development
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: production
          tags: ${{ env.IMAGE_PROD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
